management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: always

spring:
  cache:
    cache-names: cache1
    caffeine:
     spec: maximumSize=1000,expireAfterWrite=10m

rate-limit:
  capacity: 10
  refill-tokens: 10
  refill-duration: 1m
  cache-max-size: 10000
  cache-expire-after: 10m